### ISSUE TITLE
rollup() no longer allows empty inputs since 1.3.0

### ISSUE THREAD

**Issue by vorbei** [uwdata/arquero#64] opened 2020-12-20 15:23 UTC
In previous versions, by using someTable.groupby('colA','colB').rollup(), it is possible to return a result table with all unique values with valid groups without actually rollup a value. However in 1.3.0, this is broken since the 'Object.entries are not allowed for undefined or null' error(depends on the browser). I have to manually add anything like op.count() to get it work, which I actually don't need.

I don't know if it is by purpose or by accident. But I do think the previous usage is no big deal for rollup() function.

**Comment by vorbei** [comment] 2020-12-20 15:30
update: I found by using rollup({}) it's possible to get what I did in previous versions (get the keys without real aggregations). But it's still another hacky input pattern?

**Comment by jheer** [comment] 2020-12-20 15:53
Thanks for sharing! The issue is already fixed in master, but needs to be released. Coming soon...

**Comment by jheer** [comment] 2020-12-20 22:27
Fixed and added tests, released in 1.3.0.

**Closed by jheer** 2020-12-20 22:27 UTC
Labels: bug
