### ISSUE TITLE
Update table getters to respect filter and order criteria?

### ISSUE THREAD

**Issue by ericemc3** [uwdata/arquero#94] opened 2021-02-08 20:54 UTC
I am troubled with the fact that get() ignores current filter, making it (a little bit) difficult to access data in a filtered/ordered table.

And i am also having that strange result here (undefined when i expect 4 or ideally 5):

```
const dt = aq.table({ a: [1, 2, 3], b: ["4", "5", "6"] })

dt.filter(d => d.a > 1)
  .derive({b: d => +d.b})
  .column('b').get(0) 
```

**Comment by jheer** [comment] 2021-02-09 09:28
Technically this issue is a duplicate of previous issues, but as multiple folks are stumbling on the current design we can consider changing it. We could update table `get()` and `getter()` to use row indices based on the filtered and ordered data (1..numRows), rather than directly access the backing data (1..totalRows). This would be a breaking change requiring a major version update, as well as modifications to the Arquero + D3 tutorial notebook.

**Comment by jheer** [comment] 2021-02-09 09:31
As for the `undefined` in the example above:

* The derive verb creates a new column `b` that replaces the previous column `b`.
* Filtered rows are skipped when creating the new column.
* As the first row is filtered, it is never assigned a value in the new `b` column, hence it is `undefined`.

**Comment by ericemc3** [comment] 2021-02-09 17:11
Thank you for these explanations and once again for your openness!

**Closed** 2021-02-16 09:14 UTC
Labels: enhancement
