### ISSUE TITLE
TypeScript type errors for op methods.

### ISSUE THREAD

**Issue by thielium** [uwdata/arquero#182] opened 2021-05-19 20:35 UTC
**Problem**

TypeScript compiler complains when using `op` as [documented](https://uwdata.github.io/arquero/api/verbs#rollup).

However, the library functions correctly.

**Steps to reproduce**

```
import * as aq from "arquero";

aq.from([{ a: 1 }, { a: 2 }])
  // Error: Type 'number' is not assignable to type 'string | TableExpr'. ts(2322)
  .rollup({ max: aq.op.sum("a") })
  .objects();
```

**Expected Behavior**

No compiler error

**Comment by thielium** [comment] 2021-05-19 20:35
(Thanks for a great lib!)

**Comment by jheer** [comment] 2021-05-19 21:42
Thanks! The types are indeed wrong here. I'll look into fixing this soon.

**Comment by thielium** [comment] 2021-05-20 12:14
Much obliged!

**Comment by jheer** [comment] 2021-05-20 12:20
Fix released in v4.7.1. Please share if you see additional issues. (I'm not a TypeScript expert and also not using it directly, as Arquero generates the types from the JSDoc comments...)

**Comment by keckelt** [comment] 2021-05-26 06:37
Hi @jheer,

I'm adding up two `op.sum`s, which now fails:
```js
aqData.derive({foobar: rolling((d) => op.sum(d.foo) + op.sum(d.bar))})
```

but I guess there should be no difference to writing:

```js
aqData.derive({foobar: rolling((d) => op.sum(d.foo + d.bar))})
```

**Comment by jheer** [comment] 2021-05-26 08:41
Thanks for pointing this out. This is a regression due to the more recent "fixes". I'll need to look into what support (if any) `tsc` has for defining overloaded functions from JSDoc.

**Closed** 2021-05-28 08:33 UTC
Labels: bug
